semi: true
singleQuote: true
arrowParents: always
proseWrap: always
endOfLine: lf

overrides:
    - files:
          - ".*.{yml,yaml}"
          - "*.{yml,yaml}"
      options:
          tabWidth: 4
          singleQuote: false
