matrix:
    include:
        # Linters
        ## Golangci
        - language: go
          go:
              - "1.12"
          install:
              - curl -sfL
                https://install.goreleaser.com/github.com/golangci/golangci-lint.sh
                | sh -s -- -b $(go env GOPATH)/bin v1.17.1
          before_script:
              - golangci-lint --version
          script:
              - golangci-lint run

        ## Prettier
        - language: node_js
          node_js:
              - "12"
          cache:
              npm: true
          script:
              - npm run lint
